version: "3.9"
services:
  db:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    restart: always
    env_file: ./server/docker.env

  nest-server:
    container_name: nest-server
    build:
      context: ./server
    ports:
      - 4000:4000
    depends_on:
      - db
    env_file: ./server/docker.env

  next-client:
    container_name: next-client
    build:
      context: ./client
    ports:
      - "3000:3000"
    depends_on:
      - nest-server
